# Generated by Django 4.2.3 on 2023-11-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ver_code',
            field=models.CharField(default='980140090303', max_length=15, verbose_name='код из письма'),
        ),
    ]
