# Generated by Django 4.2.3 on 2023-11-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code_auto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code_user',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='код верификации'),
        ),
    ]
