# Generated by Django 4.2.3 on 2023-11-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_verification_user_verification_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='верификация почты'),
        ),
        migrations.AddField(
            model_name='user',
            name='ver_code',
            field=models.CharField(default='487628053090', max_length=15, verbose_name='код из письма'),
        ),
    ]
