# Generated by Django 4.2.3 on 2023-11-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_verification_code_user_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ver_code',
            field=models.CharField(default='837906432953', max_length=15, verbose_name='код из письма'),
        ),
    ]
