# Generated by Django 4.1 on 2023-07-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=None, upload_to='', verbose_name='Изображение (превью)'),
        ),
    ]
