# Generated by Django 4.1 on 2023-08-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_is_active',
            field=models.BooleanField(verbose_name='активность версии'),
        ),
    ]
